[mariadb]
address  = "127.0.0.1"
username = "admin"
password = "Cas2020"
port     = 3306
database = "casorder"
[server]
ip = "0.0.0.0"
port = 8090
[redis]
address = "127.0.0.1"
port = 6379
[environment]
mode = "dev"
[logging]
mode = "debug"
logFolder = "/home/khanhct/logs"
logFile = "casorder.log"
[token]
key="secret"
expire = 2
[grpc]
host = "127.0.0.1"
port = "50051"
[miq_grpc]
host = "58.186.85.19"
port = "50052"
[mail_grpc]
host = "127.0.0.1"
port = "50051"
